import axios from 'axios';
import Head from 'next/head'
import { useSelector } from 'react-redux';
import { selectBook, setBook } from '../store/book/bookSlice';
import { wrapper } from '../store/store';

export default function Home(props: any) {
    const book = useSelector(selectBook);
    return (
        <>
            <Head>
                <title>{`${props.title} - Book`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <header style={{ height: '64px', backgroundColor: 'black', color: 'white' }}>Books</header>
                {JSON.stringify(book)}
            </main>
        </>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
    (store) =>
        async ({ query }) => {
            if (query.q) {
                const response = await axios.get('http://localhost:3000/api/bookList');
                store.dispatch(setBook(response.data));
            } else {
                store.dispatch(setBook({}));
            }
            // we can set the initial state from here
            // we are setting to false but you can run your custom logic here
            return {
                props: {
                    title: query.q || 'Search'
                }
            };
        }
);
  